server:
  port: 8081    # or any other available port

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Student_db?createDatabaseIfNotExist=true
    username: root
    password: 0819
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop   # can be: create, create-drop, update, validate, none
    database: mysql
    show-sql: true
